
import { Metadata } from 'next';
import  { UrlShortnerPageComp } from '../components/urlShortnerComp';

const UrlShortnerPage = () => {
  return(
    <UrlShortnerPageComp />
  )
}

export const metadata: Metadata = {
  title: "Url Shortner App",
  description: "Generated by Lord Miraj",
};


export default UrlShortnerPage;