
import { Metadata } from 'next';
import  { UrlShortnerPageComp } from '../components/urlShortnerComp';
import RightReserved from '../components/common/rightReserved';
const UrlShortnerPage = () => {
  return(
    <>
    <UrlShortnerPageComp />
    <RightReserved />
    </>
  )
}

export const metadata: Metadata = {
  title: "Url Shortner App",
  description: "Generated by Lord Miraj",
};


export default UrlShortnerPage;